name: CMake Ubuntu

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: "lint"
      run: |
        sudo apt-get update
        sudo apt-get install -y shfmt shellcheck
        ./phare-mpi-cuda/lint.sh
        ./phare-mpi-rocm/lint.sh
